# Practicing Numpy

In [3]:
import numpy as np

In [4]:
# A single dimension array can be created by using np.array method and supplying the values in [ ]
my_array = np.array([1, 2, 3, 4, 5])

In [5]:
my_array

array([1, 2, 3, 4, 5])

In [6]:
# Returns the type of the array normally it will be ndarray
type(my_array)

numpy.ndarray

In [7]:
# Returns the data type of the values
my_array.dtype

dtype('int32')

In [8]:
# Returns the dimensions of the array
my_array.ndim

1

In [9]:
# Returns the shape of the array, in this case 5 columns
my_array.shape

(5,)

In [10]:
# Returns the size of the array
my_array.size

5

In [11]:
# 2D arrays can also be created by supplying values in this format [ [ ], [ ] ]
my_2d_array = np.array([[1, 2, 3, 4], [1, 4, 9, 16]])

In [12]:
my_2d_array

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [13]:
my_2d_array.dtype

dtype('int32')

In [14]:
type(my_2d_array)

numpy.ndarray

In [15]:
my_2d_array.size

8

In [16]:
my_2d_array.shape

(2, 4)

In [17]:
my_2d_array.ndim

2

In [18]:
# Returns the size in bytes for each item
my_array.itemsize

4

In [19]:
my_2d_array.itemsize

4

In [20]:
my_array.data

In [21]:
# Can have more than 2D, in this case its 3D and that two in the form of list and tuples
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
e.dtype

dtype('int32')

In [23]:
type(e)

numpy.ndarray

In [24]:
e.size

9

In [25]:
e.data

In [26]:
e.itemsize

4

In [27]:
e.shape

(3, 3)

In [28]:
e.ndim

2

In [29]:
# Arrays can also contain string values
str_array = np.array([['a','b'],['c','d']])

In [30]:
str_array.ndim

2

In [31]:
str_array.size

4

In [32]:
# The dtype would return <U1 as in unicode
str_array.dtype

dtype('<U1')

In [33]:
# To get the real dtype use dtype.name
str_array.dtype.name

'str32'

In [34]:
str_array

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [35]:
# It is also possible to specifiy the dtype while creating the ndarray
c = np.array([1.2, 2.3, 3.0], dtype=complex)

In [36]:
c.dtype

dtype('complex128')

In [37]:
c

array([1.2+0.j, 2.3+0.j, 3. +0.j])

In [38]:
# A ndarray can also be created by initializing it with 0s using zeros and then specifying the dimensions
z = np.zeros([5, 5])

In [39]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
# A ndarray can also be created by initializing it with 1s using ones and then specifying the dimensions
o = np.ones([3, 3])

In [41]:
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
# An arange method can be used to initialize a ndarray with values within the provided ranges
a = np.arange(0,10)

In [43]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# arange method also allows for increments as a third parameter which can be float
s = np.arange(0, 10, 2)

In [45]:
s

array([0, 2, 4, 6, 8])

In [46]:
# arange method allows for multi-dimensional arrays with initialization but must be used with reshape method
d = np.arange(0, 9).reshape(3,3)

In [47]:
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
# linspace method can be used for creating arrays with 3rd parameter telling how many elements to generate
l = np.linspace(2, 10, 5)

In [49]:
l

array([ 2.,  4.,  6.,  8., 10.])

In [50]:
# Randome numbers array can also be generated with dimensions using random.random
r = np.random.random([3, 3])

In [51]:
r

array([[0.11403968, 0.11914053, 0.76853837],
       [0.1455684 , 0.96283204, 0.21614615],
       [0.51616793, 0.63335307, 0.75826752]])

## Arithematic Operations

In [52]:
ar = np.arange(4)

In [53]:
ar

array([0, 1, 2, 3])

In [54]:
# Arithematic operations can be performed on ndarrays like multiplying each element of the array by 4
ar * 4

array([ 0,  4,  8, 12])

In [55]:
ar2 = np.arange(0, 6)

In [56]:
ar3 = np.arange(1, 7)

In [57]:
ar2

array([0, 1, 2, 3, 4, 5])

In [58]:
ar3

array([1, 2, 3, 4, 5, 6])

In [85]:
# Similarly two ndarrays can be added in which each element from one array will be added to corresponding element in other array
ar = ar2 + ar3

In [60]:
ar

array([ 1,  3,  5,  7,  9, 11])

In [86]:
# Mathematical operations like sin can also be performed on ndarray. It will return a ndarray
arsin = np.sin(ar2)

In [87]:
arsin

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [88]:
type(arsin)

numpy.ndarray

In [64]:
# Similarly operations like square root can be applied that would result in sq.rt of each element of the array
type(np.sqrt(ar3))

numpy.ndarray

## Indexing

In [65]:
a = np.array([1, 2, 3, 4, 5])

In [66]:
# ndarray can have indexing like other programming languages
a[1]

2

In [67]:
# multiple indexing positions can be applied but in a format [ [ ] ]
a[[1, 3, 4]]

array([2, 4, 5])

In [89]:
A = np.arange(0, 9).reshape(3, 3)

In [90]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
# Indexing can be applied to multi-dimensional ndarrays where first index is row and second is a column
A[1][0]

3

In [91]:
# Indexing can also be applied using a comma (,) between row and column indices
A[1, 0]

3

In [72]:
B = np.arange(0,16).reshape(4, 4)

In [73]:
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
B[2, 1]

9

## Slicing

In [75]:
a = np.arange(0, 5)

In [76]:
a

array([0, 1, 2, 3, 4])

In [92]:
# Slicing can also be performed in ndarrays just like arrays and lists.
a[1:3]

array([1, 2])

In [78]:
a[-1]

4

In [79]:
# Such type of slicing means starting from location -3 and going till the end of the array
a[-3:]

array([2, 3, 4])

In [80]:
# Such slicing means start to end with an increment of 2 (or stepping on every second variable)
a[::2]

array([0, 2, 4])

In [81]:
# Such slicing will return the whole array
a[:]

array([0, 1, 2, 3, 4])

In [82]:
A = np.arange(0, 9).reshape(3, 3)

In [83]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
A[1,0]

3

In [93]:
# Such slicing means first row with all the columns in that row since after the comma : is used which means from start to end
A[0,:]

array([0, 1, 2])

In [95]:
# Such slicing means 3rd row and first element of the column where it starts the column from beginning till 2nd column but not
# including the 2nd column that would result only in the first column and hence only one element
A[2,:1]

array([6])

In [96]:
# Such slicing means all the row since using : on rows that means from start to end and after comma are the columns which is 1
# in this case that includes only the second column and hence 1, 4, 7 that has all rows and second column
A[:,1]

array([1, 4, 7])

In [97]:
# Such slicing means on rows its 0 - 2 (so rows 0 and 1) and at columns its 0 - 2 (so columns 0 and 1)
A[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [98]:
# Such slicing means rows starting from 1 to end which is 2nd and 3rd row and similarly 2nd and 3rd columns
A[1:,1:]

array([[4, 5],
       [7, 8]])

In [99]:
# Such slicing means rows from 1 till end that means 2nd and 3rd row and for columns it starts from last element to the end
# that means only one element that is the last element
A[1:,-1:]

array([[5],
       [8]])

In [182]:
# Such slicing means starting from last element of the row till end which means only last row and since there are no mention
# of columns means all the columns
A[-1:,]

array([[6, 7, 8]])

## Iterating through Array

In [100]:
a = np.arange(0, 20,2)

In [101]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [102]:
# In a single dimension ndarray elements can be cycled through using for loop
for i in a:
    print(i)

0
2
4
6
8
10
12
14
16
18


In [103]:
A = np.arange(0, 9).reshape(3, 3)

In [105]:
# In a multi-dimensional ndarray, each row can be cycled through using a for loop
for row in A:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]


In [106]:
# In a multi-dimensional ndarray, if each element is required, a .flat attribute can be used in a for loop
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
7
8


In [108]:
# apply_along_axis function can be applied on ndarray to perform some operations on axis
# first argument of the function is the operation, 
# second argument is the axis (0 for column and 1 for rows)
# third argument is the array
np.apply_along_axis(np.mean,axis=0, arr=A)

array([3., 4., 5.])

In [109]:
np.apply_along_axis(np.mean,axis=1, arr=A)

array([1., 4., 7.])

## Conditions and Boolean Arrays

In [112]:
A = np.arange(0, 9).reshape(3, 3)

In [113]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
# Boolean operations can be performed on ndarray on each element of the array
A <= 2

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [117]:
A >= 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [119]:
# ndarray has a function transpose that converts rows into columns and vice versa
A.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

## Array Manipulations

### Joining Arrays

In [120]:
A = np.ones((3, 3))

In [121]:
B = np.zeros((3, 3))

In [122]:
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [123]:
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [125]:
# This will put the elements of A stack over the B array
np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [126]:
# This will put the elements of A stacked on the left side of the B array
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [129]:
a = np.array([0, 1, 2])

In [130]:
b = np.array([3, 4, 5])

In [132]:
# This function normally works with 1-dim array where a new multi-dim array is created by providing rows
np.row_stack((a,b))

array([[0, 1, 2],
       [3, 4, 5]])

In [134]:
# This function normally works with 1-dim array where a new multi-dim array is created by providing columns
np.column_stack((a,b))

array([[0, 3],
       [1, 4],
       [2, 5]])

### Splitting Arrays

In [141]:
A = np.arange(0, 16).reshape(4, 4)

In [142]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [143]:
# This would help in splitting the ndarray horizontally into multiple arrays
[B,C] = np.hsplit(A,2)

In [144]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [145]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [146]:
# This would help in splitting the ndarray vertically into multiple arrays
[B,C] = np.vsplit(A,2)

In [147]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [148]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [157]:
[A1, A2, A3] = np.split(A, [1, 3], axis=0)

In [158]:
A1

array([[0, 1, 2, 3]])

In [159]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [160]:
A3

array([[12, 13, 14, 15]])

In [161]:
# Arrays can be copied to another array in a way that they can only copy the reference and not the actual array
a = np.array([0, 1, 2, 3, 4])

In [162]:
a

array([0, 1, 2, 3, 4])

In [163]:
b = a

In [164]:
b

array([0, 1, 2, 3, 4])

In [165]:
# Change in one array will be reflected in the other array as it is only a reference but the same array
a[1] = 5

In [166]:
a

array([0, 5, 2, 3, 4])

In [167]:
b

array([0, 5, 2, 3, 4])

In [170]:
# Slicing would create a subset of the array from the original which is still the reference
c = a[0:3]

In [171]:
c

array([0, 5, 2])

In [172]:
# In order to copy array, copy function can be used
d = a.copy()

In [173]:
d

array([0, 5, 2, 3, 4])

In [174]:
a[1] = 1

In [175]:
a

array([0, 1, 2, 3, 4])

In [176]:
d

array([0, 5, 2, 3, 4])